<?php
// app/Http/Controllers/InvoiceController.php

namespace App\Http\Controllers;

use App\Models\Invoice;
use App\Models\InvoiceItem;
use App\Models\InvoiceTerm;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\DB;

class InvoiceController extends Controller
{
    public function index()
    {
        $invoices = Invoice::with('creator')->orderBy('created_at', 'desc')->get();
        return view('invoice.index', compact('invoices'));
    }

    public function create()
    {
        // Pass empty invoice number, will be generated dynamically via AJAX
        $invoiceNumber = '';
        return view('invoice.create', compact('invoiceNumber'));
    }

    public function store(Request $request)
    {
        $request->validate([
            'invoice_number' => 'required|string|max:255|unique:invoices,invoice_number',
            'invoice_date' => 'required|date',
            'bill_to_name' => 'required|string|max:255',
            'bill_to_address' => 'required|string',
            'items' => 'required|array|min:1',
            'items.*.product_name' => 'required|string|max:255',
            'items.*.item_description' => 'required|string',
            'items.*.unit_price' => 'required|numeric|min:0',
            'items.*.tax_percentage' => 'required|numeric|min:0|max:100',
            'items.*.vat_percentage' => 'required|numeric|min:0|max:100',
            'items.*.quantity' => 'required|integer|min:1',
        ]);

        try {
            DB::beginTransaction();

            // Calculate totals
            $grandTotal = 0;
            $itemsData = [];

            foreach ($request->items as $item) {
                $unitPrice = (float) $item['unit_price'];
                $taxPercentage = (float) $item['tax_percentage'];
                $vatPercentage = (float) $item['vat_percentage'];
                $quantity = (int) $item['quantity'];

                // Calculate tax amount based on your formula
                $taxAmount = 0;
                if ($taxPercentage == 5) {
                    $taxAmount = ($unitPrice * $taxPercentage) / 95;
                } elseif ($taxPercentage == 15) {
                    $taxAmount = ($unitPrice * $taxPercentage) / 85;
                }

                // Calculate amount after tax
                $amountAfterTax = $unitPrice + $taxAmount;

                // Calculate VAT amount
                $vatAmount = ($amountAfterTax * $vatPercentage) / 100;

                // Calculate amount after VAT
                $amountAfterVat = $amountAfterTax + $vatAmount;

                // Calculate total price
                $totalPrice = $amountAfterVat * $quantity;

                $itemsData[] = [
                    'product_name' => $item['product_name'],
                    'item_description' => $item['item_description'],
                    'unit_price' => $unitPrice,
                    'tax_percentage' => $taxPercentage,
                    'tax_amount' => $taxAmount,
                    'vat_percentage' => $vatPercentage,
                    'vat_amount' => $vatAmount,
                    'quantity' => $quantity,
                    'total_price' => $totalPrice,
                ];

                $grandTotal += $totalPrice;
            }

            // Calculate advance payment
            $advancePaid = 0;
            if ($request->advance_paid_type == 'fixed') {
                $advancePaid = (float) $request->advance_paid_fixed;
            } else {
                $advancePercentage = (float) str_replace('%', '', $request->advance_paid_type);
                $advancePaid = ($grandTotal * $advancePercentage) / 100;
            }

            $restPayable = $grandTotal - $advancePaid;
            $netPayable = $restPayable;

            // Use the invoice number from the form (generated by JavaScript)
            $invoiceNumber = $request->invoice_number;

            // Create invoice
            $invoice = Invoice::create([
                'invoice_number' => $invoiceNumber,
                'invoice_date' => $request->invoice_date,
                'reference_work_order' => $request->reference_work_order,
                'bill_to_name' => $request->bill_to_name,
                'bill_to_address' => $request->bill_to_address,
                'grand_total' => $grandTotal,
                'advance_paid' => $advancePaid,
                'rest_payable' => $restPayable,
                'net_payable' => $netPayable,
                'amount_in_words' => Invoice::numberToWords($netPayable),
                'advance_paid_fixed' => $advancePaid,
                'advance_paid_type' => $request->advance_paid_type,
                'created_by' => Auth::id(),
            ]);

            // Create invoice items
            foreach ($itemsData as $index => $itemData) {
                InvoiceItem::create([
                    'invoice_id' => $invoice->id,
                    'row_order' => $index + 1,
                    ...$itemData
                ]);
            }

            // Create invoice terms
            if ($request->has('terms')) {
                foreach ($request->terms as $index => $term) {
                    if (!empty($term['term_description'])) {
                        InvoiceTerm::create([
                            'invoice_id' => $invoice->id,
                            'row_order' => $index + 1,
                            'term_description' => $term['term_description']
                        ]);
                    }
                }
            }

            DB::commit();

            return redirect()->route('invoice.index')
                ->with('success', 'Invoice created successfully.');
        } catch (\Exception $e) {
            DB::rollBack();
            return back()->with('error', 'Error creating invoice: ' . $e->getMessage());
        }
    }

    public function show(Invoice $invoice)
    {
        $invoice->load(['items', 'terms', 'creator']);
        return view('invoice.show', compact('invoice'));
    }

    public function edit(Invoice $invoice)
    {
        $invoice->load(['items', 'terms']);
        return view('invoice.edit', compact('invoice'));
    }

    public function update(Request $request, Invoice $invoice)
    {
        $request->validate([
            'invoice_number' => 'required|string|max:255|unique:invoices,invoice_number,' . $invoice->id,
            'invoice_date' => 'required|date',
            'bill_to_name' => 'required|string|max:255',
            'bill_to_address' => 'required|string',
            'items' => 'required|array|min:1',
            'items.*.product_name' => 'required|string|max:255',
            'items.*.item_description' => 'required|string',
            'items.*.unit_price' => 'required|numeric|min:0',
            'items.*.tax_percentage' => 'required|numeric|min:0|max:100',
            'items.*.vat_percentage' => 'required|numeric|min:0|max:100',
            'items.*.quantity' => 'required|integer|min:1',
        ]);

        try {
            DB::beginTransaction();

            // Calculate totals
            $grandTotal = 0;
            $itemsData = [];

            foreach ($request->items as $item) {
                $unitPrice = (float) $item['unit_price'];
                $taxPercentage = (float) $item['tax_percentage'];
                $vatPercentage = (float) $item['vat_percentage'];
                $quantity = (int) $item['quantity'];

                // Calculate tax amount based on your formula
                $taxAmount = 0;
                if ($taxPercentage == 5) {
                    $taxAmount = ($unitPrice * $taxPercentage) / 95;
                } elseif ($taxPercentage == 15) {
                    $taxAmount = ($unitPrice * $taxPercentage) / 85;
                }

                // Calculate amount after tax
                $amountAfterTax = $unitPrice + $taxAmount;

                // Calculate VAT amount
                $vatAmount = ($amountAfterTax * $vatPercentage) / 100;

                // Calculate amount after VAT
                $amountAfterVat = $amountAfterTax + $vatAmount;

                // Calculate total price
                $totalPrice = $amountAfterVat * $quantity;

                $itemsData[] = [
                    'product_name' => $item['product_name'],
                    'item_description' => $item['item_description'],
                    'unit_price' => $unitPrice,
                    'tax_percentage' => $taxPercentage,
                    'tax_amount' => $taxAmount,
                    'vat_percentage' => $vatPercentage,
                    'vat_amount' => $vatAmount,
                    'quantity' => $quantity,
                    'total_price' => $totalPrice,
                ];

                $grandTotal += $totalPrice;
            }

            // Calculate advance payment
            $advancePaid = 0;
            if ($request->advance_paid_type == 'fixed') {
                $advancePaid = (float) $request->advance_paid_fixed;
            } else {
                $advancePercentage = (float) str_replace('%', '', $request->advance_paid_type);
                $advancePaid = ($grandTotal * $advancePercentage) / 100;
            }

            $restPayable = $grandTotal - $advancePaid;
            $netPayable = $restPayable;

            // Update invoice
            $invoice->update([
                'invoice_number' => $request->invoice_number,
                'invoice_date' => $request->invoice_date,
                'reference_work_order' => $request->reference_work_order,
                'bill_to_name' => $request->bill_to_name,
                'bill_to_address' => $request->bill_to_address,
                'grand_total' => $grandTotal,
                'advance_paid' => $advancePaid,
                'rest_payable' => $restPayable,
                'net_payable' => $netPayable,
                'amount_in_words' => Invoice::numberToWords($netPayable),
                'advance_paid_fixed' => $advancePaid,
                'advance_paid_type' => $request->advance_paid_type,
            ]);

            // Delete existing items and terms
            $invoice->items()->delete();
            $invoice->terms()->delete();

            // Create new invoice items
            foreach ($itemsData as $index => $itemData) {
                InvoiceItem::create([
                    'invoice_id' => $invoice->id,
                    'row_order' => $index + 1,
                    ...$itemData
                ]);
            }

            // Create new invoice terms
            if ($request->has('terms')) {
                foreach ($request->terms as $index => $term) {
                    if (!empty($term['term_description'])) {
                        InvoiceTerm::create([
                            'invoice_id' => $invoice->id,
                            'row_order' => $index + 1,
                            'term_description' => $term['term_description']
                        ]);
                    }
                }
            }

            DB::commit();

            return redirect()->route('invoice.index')
                ->with('success', 'Invoice updated successfully.');
        } catch (\Exception $e) {
            DB::rollBack();
            return back()->with('error', 'Error updating invoice: ' . $e->getMessage());
        }
    }

    public function destroy(Invoice $invoice)
    {
        try {
            $invoice->items()->delete();
            $invoice->terms()->delete();
            $invoice->delete();

            return redirect()->route('invoice.index')
                ->with('success', 'Invoice deleted successfully.');
        } catch (\Exception $e) {
            return back()->with('error', 'Error deleting invoice: ' . $e->getMessage());
        }
    }

    // AJAX method to get sequence number (for create page)
    public function getSequence(Request $request)
    {
        try {
            $companyName = $request->company_prefix;
            $invoiceDate = $request->invoice_date;

            if (!$companyName || !$invoiceDate) {
                return response()->json([
                    'success' => false,
                    'message' => 'Company name and date are required'
                ]);
            }

            // Generate invoice number using the model method
            $invoiceNumber = Invoice::generateInvoiceNumber($companyName, $invoiceDate);

            // Extract sequence from the generated number
            $parts = explode('-', $invoiceNumber);
            $sequence = end($parts);

            return response()->json([
                'success' => true,
                'sequence' => $sequence,
                'invoice_number' => $invoiceNumber
            ]);
        } catch (\Exception $e) {
            return response()->json([
                'success' => false,
                'message' => $e->getMessage()
            ]);
        }
    }
    // AJAX method to get invoice number
    public function getInvoiceNumber(Request $request)
    {
        try {
            $companyName = $request->bill_to_name;
            $invoiceDate = $request->invoice_date;

            if (!$companyName || !$invoiceDate) {
                return response()->json([
                    'success' => false,
                    'message' => 'Company name and date are required'
                ]);
            }

            // Generate invoice number using the model method
            $invoiceNumber = Invoice::generateInvoiceNumber($companyName, $invoiceDate);

            return response()->json([
                'success' => true,
                'invoice_number' => $invoiceNumber
            ]);
        } catch (\Exception $e) {
            return response()->json([
                'success' => false,
                'message' => $e->getMessage()
            ]);
        }
    }
}
